#CoreCLI YAML Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml

pool:
  vmImage: 'Ubuntu 16.04'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'Subscriber/Subscriber.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'Subscriber/Subscriber.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: publish -output $(Build.ArtifactStagingDirectory)
    #projects: 'Subscriber/Subscriber.csproj'
    #publishWebProjects: True
    #arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    #zipAfterPublish: True

- task: PublishBuildArtifacts@1