pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Running build...

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'Subscriber/Subscriber.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'Subscriber/Subscriber.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
